#!/usr/bin/env bash

alias l="ls -hlAG"
alias gs="git status"
alias gc="git checkout"
alias ga="git commit --amend --no-edit"
alias gpo='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias gpfo='git push origin +$(git rev-parse --abbrev-ref HEAD)'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset %Creset%Cblue%an%Creset %s %Cgreen(%cr)%Cred%d%Creset' --abbrev-commit --date=relative --max-count=15"
alias rgc="rg -C 30"
